### ISSUE TITLE
Errors trying to build demo on Ubuntu

### ISSUE THREAD

**Issue by geocentricllc** [LairdCP/Pinnacle_100_OOB_Demo_Manifest#1]
I'm getting the following errors when trying to build the demo project on Ubuntu:

Env:
ZEPHYR_TOOLCHAIN_VARIANT=zephyr
ZEPHYR_SDK_INSTALL_DIR=/home/zephyr/zephyr-sdk-0.11.3
Project dir: /home/zephyr/demo

**zephyr@parallels-Parallels-Virtual-Platform:~/demo$ west build -b pinnacle_100_dvk -d oob_demo/build oob_demo/oob_demo**
source directory: /home/zephyr/demo/oob_demo/oob_demo
build directory: /home/zephyr/demo/oob_demo/build (created)
BOARD: pinnacle_100_dvk
Zephyr version: 1.14.2
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3.4") 
-- Selected BOARD pinnacle_100_dvk
CMake Error at /home/zephyr/demo/zephyr/cmake/toolchain/zephyr/host-tools.cmake:47 (include):
  include could not find load file:

    /home/zephyr/demo/zephyr/cmake/toolchain/zephyr/0.11/host-tools.cmake
Call Stack (most recent call first):
  /home/zephyr/demo/zephyr/cmake/host-tools.cmake:3 (include)
  /home/zephyr/demo/zephyr/cmake/app/boilerplate.cmake:382 (include)
  CMakeLists.txt:2 (include)

-- Found west: /home/zephyr/.local/bin/west (found suitable version "0.7.3", minimum required is "0.5.6")
CMake Error at /home/zephyr/demo/zephyr/cmake/toolchain/zephyr/generic.cmake:7 (include):
  include could not find load file:

    /home/zephyr/demo/zephyr/cmake/toolchain/zephyr/0.11/generic.cmake
Call Stack (most recent call first):
  /home/zephyr/demo/zephyr/cmake/generic_toolchain.cmake:59 (include)
  /home/zephyr/demo/zephyr/cmake/app/boilerplate.cmake:398 (include)
  CMakeLists.txt:2 (include)

-- Loading /home/zephyr/demo/zephyr/boards/arm/pinnacle_100_dvk/pinnacle_100_dvk.dts as base
-- Overlaying /home/zephyr/demo/zephyr/dts/common/common.dts
CMake Error at /home/zephyr/demo/zephyr/cmake/dts.cmake:126 (message):
  command failed with return code: No such file or directory
Call Stack (most recent call first):
  /home/zephyr/demo/zephyr/cmake/app/boilerplate.cmake:399 (include)
  CMakeLists.txt:2 (include)

-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/bin/cmake -B/home/zephyr/demo/oob_demo/build -S/home/zephyr/demo/oob_demo/oob_demo -GNinja -DBOARD=pinnacle_100_dvk

**Comment by thedjnK** [comment]
For now, would you be able to retry this using the Zephyr 0.10 SDK as 0.11 is not supported (support will be added soon). Download link for the 0.10 SDK: https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.10.3

**Comment by geocentricllc** [comment]
That did it!  Thx.
